[project]
name = "ctt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "diffrax>=0.7.0",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.7",
    "jax>=0.4.30",
    "jaxopt>=0.8.5",
    "jaxtyping>=0.2.36",
    "lineax>=0.0.7",
    "matplotlib>=3.9.4",
    "optax>=0.2.4",
    "scikit-tt",
    "setuptools>=75.8.0",
    "tqdm>=4.67.1",
]


[tool.ruff.lint]
ignore = ["F722", "F821"]

[tool.uv.sources]
scikit-tt = { git = "https://github.com/PGelss/scikit_tt" }

[dependency-groups]
dev = [
    "ipython>=8.18.1",
    "line-profiler>=5.0.0",
]
